[[language]]
name = "rust"

# If this doesn't work, you might be on a older release version which handles this differently.
# Try using [language.config.check] instead of [language-server.rust-analyzer.config.check]
[language-server.rust-analyzer.config.check]
command = "clippy"
args = ["--", "-W clippy::unwrap_used", "-W clippy::expect_used", "-W clippy::pedantic", "-W clippy::nursery", "-Dwarnings"]

[[language]]
name = "typst"

[language-server.typst-lsp]
config = { exportPdf = "never" }
