- hosts: localhost
  vars:
    ansible_user: sim
  # vars:
  #   source_key: "./.ssh/id_rsa"
  #   dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"
  #   personal: "{{ lookup('env', 'HOME') }}/personal"
  tasks:
    # - include: tasks/core-setup.yml
    # - include: tasks/ssh.yml
    - include: tasks/yay-setup.yml
    - include: tasks/git-setup.yml
    - include: tasks/packages.yml
    - include: tasks/shell-setup.yml
    - include: tasks/node-setup.yml
    - include: tasks/pop-shell-setup.yml
    # - include: tasks/zsh-setup.yml
    # - include: tasks/slack-setup.yml
    # - include: tasks/personal-projects.yml
    # - include: tasks/nvim-setup.yml
    # - include: tasks/brave.yml
    # - include: tasks/debugger.yml
    # - include: tasks/dotfiles.yml
    # - include: tasks/productivity-tools.yml
    # - include: tasks/lsp.yml

