- name: Change monospace font
  command: gsettings set org.gnome.desktop.interface monospace-font-name 'Iosevka'
  become_user: "{{ ansible_user }}"

- name: Update shortcuts
  command: fish tasks/shortcuts.fish

- name: Tweaks
  command: fish tasks/tweaks.fish

- name: Extension settings
  command: fish tasks/extension-settings.fish

- name: Ensure alacritty directory exists
  file:
    dest: "~/.config/alacritty"
    state: directory

- name: Move alacritty config
  copy:
    src: "config/alacritty.yml"
    dest: "~/.config/alacritty/alacritty.yml"

- name: Ensure fish directory exists
  file:
    dest: "~/.config/fish"
    state: directory

- name: Move fish config
  copy:
    src: "config/config.fish"
    dest: "~/.config/fish/config.fish"

- name: Set gtk theme
  command: fish -c "set -U GTK_THEME 'Adwaita-dark'"
