- name: Dependencies
  community.general.pacman:
    name:
      - git
  become: yes
- name: Git setup email
  git_config:
    name: user.email
    scope: global
    value: "simon.ras.and@gmail.com"
  tags:
  - git
- name: Git setup name
  git_config:
    name: user.name
    scope: global
    value: "Simon Rask"
  tags:
  - git
