- name: Check that nvm is in PATH
  command: fish -c "nvm"
  register: nvm_check
  ignore_errors: yes

- name: nvm installation
  when: nvm_check.rc != 0
  become_user: "{{ ansible_user }}"
  block:
    - name: Install nvm
      command: fish -c "fisher install jorgebucaran/nvm.fish"

    - name: Install node
      command: fish -c "nvm install lts"

    - name: Use lts as default
      command: fish -c "set -Ux nvm_default_version lts"

    - name: Install yarn
      command: fish -c "nvm use lts && npm install -g yarn"

    - name: Update global yarn packages
      command: fish -c "nvm use lts && yarn global upgrade"

    - name: Add yarn bin to fish path
      command: fish -c "fish_add_path ~/.yarn/bin"
      ignore_errors: yes
