- name: Full system upgrade
  community.general.pacman:
    update_cache: true
    upgrade: true
  become: yes

- name: AUR packages
  command: yay -S {{ item }} --noconfirm
  with_items:
    - visual-studio-code-bin
    - gnome-shell-extension-caffeine-git
    - gnome-shell-extension-blur-my-shell
    - spotify-adblock-git
  tags:
    - desktop

- name: Pacman packages (desktop)
  community.general.pacman:
    name:
      - alacritty
      - discord
      - evince
      - firefox
      - foliate
      - ttc-iosevka
      - ttf-hack-nerd
      - xournalpp
  become: yes
  tags:
    - desktop

- name: Pacman packages (nogui)
  community.general.pacman:
    name:
      - base-devel
      - exa
      - fish
      - git
      - pdfslicer
      - pdftk
      - pdftricks
      - tldr
      - neovim
      - xclip
      - ripgrep
  become: yes


- name: Update yay packages
  command: yay --noconfirm
