- name: Full system upgrade
  community.general.pacman:
    update_cache: true
    upgrade: true
  tags:
    - install
    - core
  become: yes

- name: Check if code is in PATH
  command: "which code"
  register: code_check
  ignore_errors: yes

- name: Install code
  command: yay -S visual-studio-code-bin --noconfirm
  become_user: "{{ ansible_user }}"
  when: code_check.rc != 0

- name: Pacman packages
  community.general.pacman:
    name:
      - firefox
      - alacritty
      - evince
      - exa
      - fish
      - foliate
      - git
      - pdfslicer
      - pdftk
      - pdftricks
      - tldr
      - ttc-iosevka
      - xournalpp
      - discord
      - base-devel
      - ttf-hack-nerd
  become: yes

- name: Update yay packages
  command: yay --noconfirm
