- name: Full system upgrade
  community.general.pacman:
    update_cache: true
    upgrade: true
  become: yes

- name: AUR packages
  command: yay -S {{ item }} --noconfirm
  with_items:
    - visual-studio-code-bin
    - gnome-shell-extension-caffeine-git
    - gnome-shell-extension-blur-my-shell
    - spotify-adblock-git

- name: Pacman packages
  community.general.pacman:
    name:
      - alacritty
      - base-devel
      - discord
      - evince
      - exa
      - firefox
      - fish
      - foliate
      - git
      - pdfslicer
      - pdftk
      - pdftricks
      - tldr
      - ttc-iosevka
      - ttf-hack-nerd
      - xournalpp
      - neovim
      - xclip
  become: yes

- name: Update yay packages
  command: yay --noconfirm
