- name: Install typescript
  command: fish -c "nvm use lts && yarn global add typescript"
  become_user: "{{ ansible_user }}"

- name: Clone pop shell repo
  git:
    repo: "https://github.com/pop-os/shell"
    dest: "~/pop-shell"
    version: master_jammy
  become_user: "{{ ansible_user }}"

- name: Install pop shell
  command: echo y | make local-install
  args:
    chdir: "~/pop-shell"