- name: Check if rustup is installed
  command: which rustup
  register: rustup_installed
  ignore_errors: true
  tags:
    - wsl

- name: Rustup installation
  when: rustup_installed.rc != 0
  tags:
    - wsl
  block:
    - name: Install rustup
      command: fish -c "curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y"

    - name: Add rustup to path
      command: fish -c "fish_add_path ~/.cargo/bin"

    - name: Install rust
      command: fish -c "rustup install stable"

- name: Update rust
  command: fish -c "rustup update"
  tags:
    - wsl 
